# Renders README.md from the slurped stars.jsonl.
# Usage: jq -rsf scripts/readme.jq --arg user <username> stars.jsonl > README.md

# Make text safe for a single Markdown table cell
def cell:
  (. // "")
  | gsub("^\\s+|\\s+$"; "")
  | gsub("\\s*[\\r\\n]+\\s*"; " ")
  | gsub("<"; "&lt;")
  | gsub(">"; "&gt;")
  | gsub("\\|"; "\\|");

# GitHub heading anchors: lowercase, strip punctuation, spaces to hyphens, dedupe with -1, -2...
def slugs:
  reduce .[] as $heading ({seen: {}, out: []};
    ($heading | ascii_downcase | gsub("[^\\p{L}\\p{N} _-]"; "") | gsub(" "; "-")) as $slug
    | .out += [if .seen[$slug] then "\($slug)-\(.seen[$slug])" else $slug end]
    | .seen[$slug] += 1)
  | .out;

map(.language //= "Others") as $repos
| ($repos | group_by(.language)) as $groups
| ($groups | map(.[0].language) | slugs) as $slugs
| (now | gmtime | "\(.[2])--\(.[1] + 1)--\(.[0])") as $date
| [
    "# Awesome Stars [![Awesome](https://cdn.rawgit.com/sindresorhus/awesome/d7305f38d29fed78fa85652e3a63e154dd8e8829/media/badge.svg)](https://github.com/sindresorhus/awesome)",
    "",
    "> A curated list of my GitHub stars! Generated by [scripts/update.sh](scripts/update.sh)",
    "",
    "![Total](https://img.shields.io/badge/Total-\($repos | length)-green.svg)",
    "![Updated](https://img.shields.io/badge/Updated-\($date)-blue.svg)",
    "",
    "## 🏠 Contents",
    "",
    (range($groups | length) as $i | "- [\($groups[$i][0].language) (\($groups[$i] | length))](#\($slugs[$i]))"),
    ($groups[] |
      "",
      "## \(.[0].language)",
      "|  | Name \t|  Description \t| Author  \t|",
      "|---\t|---\t|---\t|---\t|",
      (to_entries[] | "| \(.key + 1) |  [\(.value.name)](\(.value.url)) | \(.value.description | cell) | \(.value.owner) |"),
      "",
      "**[⬆ Back to Index](#-contents)**"
    ),
    "",
    "## 📝 License",
    "",
    "To the extent possible under law, [\($user)](https://github.com/\($user)) has waived all copyright and related or neighboring rights to this work."
  ]
| join("\n")
